// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knxyrtxjzhkgsmhqifws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueHlydHhqemhrZ3NtaHFpZndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTI5MTYsImV4cCI6MjA2MzgyODkxNn0.EugP2bc2Lasm8Y2L-NCG2BJOXB0sMZiW9JqQK1z04vQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);